"use client";

import { useEffect, useRef, useState, type CSSProperties } from "react";
import { Moon, Sparkles, Code2, BrainCircuit, Feather, Globe2, GraduationCap, Users, Layers3, ExternalLink, ChevronDown, Plus, MapPin } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";

function Github({size=20,strokeWidth=1.6}:{size?:number;strokeWidth?:number}) {return <svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M9 19c-4.3 1.4-4.3-2.5-6-3m12 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 19 4.77 5.07 5.07 0 0 0 18.91 1S17.73.65 15 2.48a13.38 13.38 0 0 0-7 0C5.27.65 4.09 1 4.09 1A5.07 5.07 0 0 0 4 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 8 18.13V22"/></svg>}
function Linkedin({size=20,strokeWidth=1.6}:{size?:number;strokeWidth?:number}) {return <svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-4 0v7h-4V9h4v2"/><rect x="2" y="9" width="4" height="12"/><circle cx="4" cy="4" r="2"/></svg>}

const github = "https://github.com/yupitsmegd7";
const linkedin = "https://www.linkedin.com/in/gourav-dutta-958892299/";
const chapters = [{id:"about",label:"About me",n:"I"},{id:"work",label:"Selected work",n:"II"},{id:"craft",label:"The craft",n:"III"},{id:"journey",label:"My journey",n:"IV"},{id:"contact",label:"Connect",n:"V"}];
type Project = {name:string;repo:string;category:string;subtitle:string;description:string;stack:string[];details:string;focus:string[];note?:string;live?:string;mark:string;color:string};
const projects: Project[] = [
 {name:"Vatavarnam",repo:"Vatavarnam",category:"AI & data",subtitle:"Reading the atmosphere",description:"A 72-hour air-quality forecasting project for Delhi NCR, bringing pollution history and weather into one interface.",stack:["Python","scikit-learn","Flask","React"],details:"Built around the air pollution–weather forecasting challenge, Vatavarnam explores how meteorology and historical pollution can inform a useful air-quality outlook. It connects modelling work to a visual dashboard and interactive pollution maps.",focus:["Weather and pollutant inputs","Forecasting experiments","Interactive geographic context"],note:"An evolving research project; model forecasts are not official air-quality advisories.",live:"https://vatavarnam-1.onrender.com/",mark:"V",color:"green"},
 {name:"Prithvi",repo:"Prithvi-Disaster_Management",category:"AI & data",subtitle:"Evidence before prediction",description:"An India-focused disaster observatory with environmental feeds, historical evidence, and preparedness simulations.",stack:["TypeScript","React","Python","scikit-learn"],details:"Prithvi connects five hazard views with transparent screening rules, source-linked data, and practical preparedness learning. Separate rainfall and dry-week experiments make room for reproducible machine-learning work alongside the interface.",focus:["Five environmental hazard views","Historical evidence and data exports","Preparedness scenarios and guides"],note:"Research prototype, not an official warning service. It does not predict future earthquakes.",mark:"P",color:"blue"},
 {name:"Local",repo:"Local",category:"Web experiences",subtitle:"Everyday files, thoughtfully handled",description:"A browser-based conversion and creative toolbox for documents, images, audio, and video.",stack:["React","Vite","FFmpeg.wasm","Tesseract.js"],details:"Local brings everyday file tasks into one place. Files are processed on the device, with batch conversion, English and Hindi OCR, and a set of creative utilities. Document modes make the trade-off between keeping appearance and editing text explicit.",focus:["500 MB combined batch queue","Document layout modes and OCR","Six creative tools"],note:"Supported formats and practical limits are documented in the repository.",live:"https://localconverter-flame.vercel.app/",mark:"L",color:"wine"},
 {name:"DSA Verse",repo:"DSA_Verse",category:"Web experiences",subtitle:"The art of learning to think",description:"An adaptive learning atelier with graded practice, spaced reviews, and a connected map of progress.",stack:["Next.js","TypeScript","React"],details:"DSA Verse turns data-structure and algorithm practice into a learning journey. Its workflow uses graded work to revisit ideas, and offers C, Java, and Python examples alongside a mistake journal and mastery map.",focus:["Sixteen topic areas","C, Java, and Python examples","Adaptive practice and spaced review"],mark:"D",color:"blue"},
 {name:"Safar-e-Rachna",repo:"Safar-e-Rachna",category:"Creative worlds",subtitle:"A home for the written word",description:"A literary journal for poems, articles, and reviews, with an author desk and a deliberate writing practice.",stack:["Next.js","TypeScript","Supabase"],details:"My interest in poetry and storytelling takes shape as a reading and publishing space. Safar-e-Rachna brings together an author profile, themed reading, fuzzy search, reader interactions, and a research–write–review rhythm.",focus:["Poems, essays, and cultural reviews","Author publishing and reader interactions","Timed writing practice"],mark:"S",color:"wine"},
 {name:"Dharma Gita",repo:"Dharma_Gita",category:"Creative worlds",subtitle:"Read. Reflect. Practice.",description:"A multilingual scripture companion connecting the Bhagavad Gita with everyday questions and habits.",stack:["JavaScript","HTML","CSS"],details:"Dharma Gita combines illustrated reading with source-linked teachings. Visitors can explore Sanskrit, Hindi, and English passages, follow curated reading paths, and reflect on how a teaching relates to everyday choices.",focus:["Eighteen Gita chapters","Mantras and curated reading paths","Daily reflection and habit practice"],live:"https://dharma-gita-five.vercel.app/",mark:"ध",color:"gold"},
 {name:"Nyaya",repo:"Nyaya",category:"Web experiences",subtitle:"Making information approachable",description:"An Indian legal-information portal with a rights atlas, official-source statistics, and practical guides.",stack:["React","TypeScript","Vinext"],details:"Nyaya makes a complex information space easier to explore through a searchable law book, a situation finder, crime statistics, and helplines. The project emphasizes official sources, clear summaries, and optional cited AI explanations.",focus:["Searchable rights and law entries","Official-source statistical views","Situation guides and helplines"],note:"An independent information project, not legal advice or a government service.",mark:"N",color:"gold"},
 {name:"Poets & Perspectives",repo:"Poets_Perspectives",category:"Creative worlds",subtitle:"A quieter kind of digital space",description:"A Renaissance-inspired reflection space with literary discoveries and an interactive lamplit day planner.",stack:["React","TypeScript","MongoDB bridge"],details:"A personal reflection project shaped by literature and the atmosphere of a writing room. It combines optional check-ins, a scrapbook, sourced poems and quotations, reading chapters, and a free-form day planner.",focus:["Literary discovery and reading room","Daily reflection and scrapbook","Interactive desk and shelf planner"],note:"A wellbeing aid with configurable storage, not a diagnostic or clinical service.",mark:"&",color:"wine"},
 {name:"Fieldwork",repo:"Simulation.io",category:"Web experiences",subtitle:"Curiosity in motion",description:"Interactive 3D experiments exploring drone flight, lunar exploration, and football trajectories.",stack:["JavaScript","Three.js","WebGL"],details:"Fieldwork makes changing conditions visible through interactive simulations. It is a space to experiment with motion, explore a scenario, and see how inputs influence what happens on screen.",focus:["Interactive 3D environments","Explorable conditions and motion","Learning through experimentation"],mark:"F",color:"green"},
];

function ExtLink({href,children,className=""}:{href:string;children:React.ReactNode;className?:string}) {return <a href={href} target="_blank" rel="noopener noreferrer" className={className}>{children}<span className="sr-only"> (opens in a new tab)</span></a>}
function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow"><span aria-hidden="true">✦</span>{children}</p>}
function SectionHeading({number,title,italic,children}:{number:string;title:string;italic:string;children?:React.ReactNode}){return <div className="section-heading"><span className="section-number">{number} / THE COLLECTION</span><h2>{title} <em>{italic}</em></h2>{children&&<p>{children}</p>}</div>}
function ProjectCard({project,index,onOpen}:{project:Project;index:number;onOpen:()=>void}) {return <button type="button" className={`project-card tone-${project.color}`} onClick={onOpen} aria-label={`Explore ${project.name}`}><div className="project-art" aria-hidden="true"><span className="project-index">STUDY {String(index+1).padStart(2,"0")}</span><span className="project-monogram">{project.mark}</span><span className="project-seal">G·D</span><span className="project-open"><Plus size={20}/></span></div><div className="project-copy"><span className="small-label">{project.category}</span><h3>{project.name}</h3><p>{project.description}</p><div className="stack">{project.stack.slice(0,3).map(s=><span key={s}>{s}</span>)}</div></div></button>}

export default function Home(){
 const [tab,setTab]=useState("about"); const [direction,setDirection]=useState(1); const [filter,setFilter]=useState("All work"); const [selected,setSelected]=useState<Project|null>(null); const progressRef=useRef<HTMLDivElement>(null);
 const artRef=useRef<HTMLDivElement>(null); const projectTrigger=useRef<HTMLElement|null>(null);
 const openProject=(project:Project)=>{projectTrigger.current=document.activeElement as HTMLElement;setSelected(project)};
 useEffect(()=>{let frame=0; const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const height=document.documentElement.scrollHeight-window.innerHeight;if(progressRef.current)progressRef.current.style.transform=`scaleX(${height>0?window.scrollY/height:0})`})};window.addEventListener("scroll",update,{passive:true});window.addEventListener("resize",update);update();return()=>{cancelAnimationFrame(frame);window.removeEventListener("scroll",update);window.removeEventListener("resize",update)}},[tab]);
 const changeTab=(next:string)=>{setDirection(chapters.findIndex(c=>c.id===next)>=chapters.findIndex(c=>c.id===tab)?1:-1);setTab(next);window.scrollTo({top:0,behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth"});};
 const goToTab=(next:string)=>{changeTab(next);requestAnimationFrame(()=>document.querySelector<HTMLButtonElement>(`[data-chapter="${next}"]`)?.focus({preventScroll:true}));};
 const activeIndex=chapters.findIndex(c=>c.id===tab);
 return <div className="portfolio"><a href="#main-content" className="skip-link">Skip to content</a><div className="reading-progress" ref={progressRef} style={{transform:"scaleX(0)"}}/><Tabs value={tab} onValueChange={changeTab} className="portfolio-tabs">
 <header className="site-header"><button className="identity" onClick={()=>goToTab("about")} aria-label="Gourav Dutta home"><span className="monogram">G<span>D</span><i>✦</i></span><span className="identity-caption">GOURAV DUTTA<small>A PERSONAL COLLECTION</small></span></button><nav aria-label="Portfolio chapters"><TabsList className="chapter-tabs" aria-label="Portfolio chapters"><span className="tab-glider" style={{transform:`translateX(${activeIndex*100}%)`}} aria-hidden="true"/>{chapters.map(c=><TabsTrigger className="chapter-tab" value={c.id} key={c.id} data-chapter={c.id}><span className="tab-roman">{c.n}.</span>{c.label}</TabsTrigger>)}</TabsList></nav><ExtLink href={linkedin} className="header-contact">Let’s talk <Linkedin size={15}/></ExtLink></header>
 <main id="main-content" tabIndex={-1} style={{"--slide-direction":direction} as CSSProperties}>
 <TabsContent value="about" className="chapter-panel"><section className="hero page-width"><div className="hero-copy"><Eyebrow>ENGINEER BY CURIOSITY. WRITER BY SOUL.</Eyebrow><h1>Gourav<br/><em>Dutta</em><span className="name-period">.</span></h1><div className="hero-rule"><span/> <span className="small-label">CODE, CURIOSITY & A LITTLE POETRY</span></div><p className="hero-intro">I build things that <em>think.</em><br/>And write things that <em>feel.</em></p><p className="hero-description">I’m a Computer Science undergraduate at KIIT University, an aspiring Machine Learning Engineer, and a writer. My world lives somewhere between the logic of an algorithm and the possibilities of a blank page.</p><div className="hero-actions"><button className="button button-gold" onClick={()=>goToTab("work")}>Explore my work <Layers3 size={16}/></button><a href="#the-story" className="text-link">More about me <ChevronDown size={15}/></a></div><div className="hero-meta"><span><MapPin size={13}/> India</span><span>KIIT · CSE ’29</span><span>Always a student</span></div></div>
 <div className="hero-visual"><div className="art-overline"><span>THE NOCTURNE COLLECTION</span><Moon size={15}/></div><div className="art-frame" ref={artRef} onPointerMove={e=>{if(e.pointerType!=="mouse"||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty("--tilt-x",`${(e.clientY-r.top-r.height/2)/r.height*-3}deg`);e.currentTarget.style.setProperty("--tilt-y",`${(e.clientX-r.left-r.width/2)/r.width*3}deg`)}} onPointerLeave={()=>{artRef.current?.style.setProperty("--tilt-x","0deg");artRef.current?.style.setProperty("--tilt-y","0deg")}}><img src="/images/nocturne.webp" alt="An original Renaissance-inspired oil painting of a marble bust, open manuscript and candle in a midnight atelier" width="1086" height="1448" fetchPriority="high"/><div className="art-vignette"/><span className="art-inscription">ARS · SCIENTIA · ANIMA</span><div className="floating-note"><span className="note-star">✦</span><span>At the intersection of<br/><em>art & possibility.</em></span></div></div><div className="art-caption"><span>01 — THE MIND BEHIND THE WORK</span><span>EST. IN CURIOSITY</span></div></div></section>
 <div className="interlude"><span>MACHINE LEARNING</span><i>✦</i><span>FULL-STACK DEVELOPMENT</span><i>✦</i><span>STORYTELLING</span><i>✦</i><span>COMMUNITY</span></div>
 <section id="the-story" className="story-section page-width"><div className="story-title"><Eyebrow>BEHIND THE PROJECTS</Eyebrow><h2>A life between<br/><em>logic & lyric.</em></h2><span className="signature">Gourav Dutta</span><div className="story-location">Siliguri roots.<br/>Bhubaneswar chapters.</div></div><div className="story-prose"><p className="lead drop-cap">I’m drawn to questions that refuse to stay inside a single discipline. How can data help us understand the air we breathe? How can an interface make something complicated feel approachable? And how can a few carefully chosen words make someone pause?</p><p>Those questions shape my work as a B.Tech Computer Science student at KIIT University, where I’m building my foundations in programming, data structures, machine learning, and software development. I enjoy the full journey of an idea: preparing data, experimenting with models, building an API, and giving the result an interface that someone can actually use.</p><p>My projects move between environmental intelligence, adaptive learning, useful everyday tools, and imaginative digital spaces. Vatavarnam explores air-quality forecasting. Prithvi brings environmental evidence and preparedness together. Local turns a browser into a practical creative toolbox. Each project is a chance to understand a little more, test an assumption, and make the next version better.</p><p>Writing is the other half of that practice. I write stories and poetry, and I’m interested in the way language creates atmosphere, clarity, and connection. That instinct finds its way into the reading rooms, literary journals, and thoughtful interfaces I build. I want software to have a clear purpose—and enough personality to be remembered.</p><p>As the OpenAI Student Collective Campus Lead at KIIT, I also bring my interest in AI into student learning and community projects. I’m working toward becoming a Machine Learning Engineer while staying open to the ideas, people, and unexpected experiments that can change how I think.</p><div className="story-pullquote">Build. Test. Understand. <em>Improve.</em><span>THE PRACTICE I KEEP COMING BACK TO</span></div></div></section>
 <section className="featured-section page-width"><div className="section-row"><SectionHeading number="II" title="A few things" italic="I’ve made."/><button className="text-link" onClick={()=>goToTab("work")}>View the collection <Layers3 size={15}/></button></div><div className="project-grid featured-grid">{[projects[0],projects[2],projects[4]].map(p=><ProjectCard key={p.repo} project={p} index={projects.indexOf(p)} onOpen={()=>openProject(p)}/>)}</div></section><section className="closing-note page-width"><Feather size={24}/><h2>Good things begin<br/>with <em>a conversation.</em></h2><button className="button button-outline" onClick={()=>goToTab("contact")}>Let’s make something meaningful</button></section></TabsContent>
 <TabsContent value="work" className="chapter-panel page-width interior"><SectionHeading number="II" title="The work." italic="The wonder.">A selection of experiments, useful tools, and worlds built from curiosity. Open a project to look a little closer.</SectionHeading><div className="work-toolbar"><div className="filter-group" aria-label="Filter projects">{["All work","AI & data","Web experiences","Creative worlds"].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?"selected":""} onClick={()=>setFilter(f)}>{f}</button>)}</div><span className="result-count" aria-live="polite">{projects.filter(p=>filter==="All work"||p.category===filter).length} pieces</span></div><div className="project-grid" key={filter}>{projects.filter(p=>filter==="All work"||p.category===filter).map(p=><ProjectCard key={p.repo} project={p} index={projects.indexOf(p)} onOpen={()=>openProject(p)}/>)}</div><div className="collection-footer"><p>There’s more in the workshop.</p><ExtLink href={github+"?tab=repositories"} className="button button-outline"><Github size={17}/> All repositories on GitHub</ExtLink></div></TabsContent>
 <TabsContent value="craft" className="chapter-panel page-width interior"><SectionHeading number="III" title="Tools of" italic="the trade.">A growing toolkit for moving from a question to a model, an interface, and a working application.</SectionHeading><div className="craft-grid">{[{icon:BrainCircuit,n:"01",title:"Intelligence & data",text:"Working with data, building baselines, and learning what a model can—and cannot—tell us.",tags:["Python","scikit-learn","NumPy","pandas","spaCy","Jupyter"]},{icon:Code2,n:"02",title:"Interfaces & systems",text:"Connecting careful interfaces to APIs and the data behind them.",tags:["React","Next.js","TypeScript","JavaScript","Node.js","Flask","FastAPI","HTML & CSS"]},{icon:Layers3,n:"03",title:"Foundations & workflow",text:"Strengthening the fundamentals and the tools that make each iteration possible.",tags:["C","C++","SQL","Git & GitHub","VS Code","MySQL"]},{icon:Feather,n:"04",title:"Words & perspective",text:"Bringing rhythm, clarity, and a sense of place into both writing and digital experiences.",tags:["Poetry","Storytelling","Articles & reviews","Creative direction"]}].map(c=><article className="craft-card" key={c.n}><div className="craft-top"><c.icon size={27} strokeWidth={1}/><span>{c.n}</span></div><h3>{c.title}</h3><p>{c.text}</p><div className="skill-tags">{c.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div><div className="method"><Eyebrow>HOW I APPROACH A NEW IDEA</Eyebrow><div className="method-grid">{[{n:"I",title:"Ask",text:"Start with a problem worth understanding."},{n:"II",title:"Build",text:"Make the smallest version that reveals something useful."},{n:"III",title:"Examine",text:"Look at the errors, limits, and experience."},{n:"IV",title:"Refine",text:"Use what I learn to make the next version better."}].map(m=><div key={m.n}><span>{m.n}</span><h3>{m.title}</h3><p>{m.text}</p></div>)}</div></div></TabsContent>
 <TabsContent value="journey" className="chapter-panel page-width interior"><SectionHeading number="IV" title="Still learning." italic="Always becoming.">Education, community, and a practice of turning curiosity into something tangible.</SectionHeading><div className="journey-layout"><div className="journey-aside"><p>Not a straight line.<br/><em>A collection of beginnings.</em></p><span>THE CHAPTER IN PROGRESS</span><GraduationCap size={42} strokeWidth={1}/></div><div className="timeline"><article><span className="timeline-dot"/><span className="small-label">2025 — 2029 · EDUCATION</span><h3>Computer Science at KIIT</h3><h4>B.Tech · Kalinga Institute of Industrial Technology</h4><p>Building foundations in algorithms, software systems, and machine learning, while applying those ideas through independent projects.</p></article><article><span className="timeline-dot"/><span className="small-label">COMMUNITY & LEADERSHIP</span><h3>OpenAI Student Collective</h3><h4>Campus Lead · KIIT</h4><p>Bringing an interest in AI into student learning, hands-on exploration, and community projects.</p></article><article><span className="timeline-dot"/><span className="small-label">CREATIVE PRACTICE</span><h3>A writer, alongside the engineer</h3><h4>Stories · Poetry · Digital reading spaces</h4><p>Exploring language through writing and giving that practice a home in projects such as Safar-e-Rachna and Poets & Perspectives.</p></article><article><span className="timeline-dot"/><span className="small-label">THE DIRECTION AHEAD</span><h3>Applied machine learning</h3><h4>Learning the complete journey</h4><p>Growing toward ML engineering: from data preparation and controlled experiments to APIs, thoughtful interfaces, and honest evaluation.</p></article></div></div><div className="journey-end"><Users size={23}/><p>Interested in learning, experimenting, or building together?</p><button className="text-link" onClick={()=>goToTab("contact")}>Let’s connect</button></div></TabsContent>
 <TabsContent value="contact" className="chapter-panel page-width interior contact-page"><Eyebrow>THE NEXT CHAPTER</Eyebrow><h2>Some ideas deserve<br/>to be <em>built together.</em></h2><p className="contact-intro">A thoughtful project, an interesting ML problem, a student initiative, or a conversation about words and the web—I’d love to hear about it.</p><div className="contact-links"><ExtLink href={linkedin} className="contact-card"><Linkedin size={28} strokeWidth={1}/><span><small>START A CONVERSATION</small><strong>Find me on LinkedIn</strong><span>Gourav Dutta</span></span><ExternalLink size={18}/></ExtLink><ExtLink href={github} className="contact-card"><Github size={28} strokeWidth={1}/><span><small>EXPLORE THE WORKSHOP</small><strong>Meet me on GitHub</strong><span>@yupitsmegd7</span></span><ExternalLink size={18}/></ExtLink></div><div className="contact-signoff"><span className="signature">Gourav Dutta</span><p>Engineer in the making. Writer at heart.</p><span className="small-label">BASED IN INDIA · CURIOUS EVERYWHERE</span></div></TabsContent>
 </main><footer className="site-footer page-width"><button onClick={()=>goToTab("about")} className="footer-brand" aria-label="Return to About me">GD<span>✦</span></button><span>© {new Date().getFullYear()} Gourav Dutta</span><span className="footer-thought">Made with intent. <em>Always evolving.</em></span><div><ExtLink href={github} className="icon-link"><Github size={18}/><span className="sr-only">GitHub</span></ExtLink><ExtLink href={linkedin} className="icon-link"><Linkedin size={18}/><span className="sr-only">LinkedIn</span></ExtLink></div></footer></Tabs>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="project-dialog" onCloseAutoFocus={event=>{event.preventDefault();projectTrigger.current?.focus()}}>{selected&&<><div className={`dialog-art tone-${selected.color}`} aria-hidden="true"><span>{selected.mark}</span><p>A STUDY IN {selected.category.toUpperCase()}</p></div><div className="dialog-body"><span className="small-label">{selected.subtitle}</span><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.description}</DialogDescription><p className="dialog-detail">{selected.details}</p><h3>Inside the project</h3><ul>{selected.focus.map(f=><li key={f}><Sparkles size={14}/>{f}</li>)}</ul><div className="skill-tags">{selected.stack.map(s=><span key={s}>{s}</span>)}</div>{selected.note&&<p className="project-note">{selected.note}</p>}<div className="dialog-links"><ExtLink href={`${github}/${selected.repo}`} className="button button-gold"><Github size={16}/> Explore the code</ExtLink>{selected.live&&<ExtLink href={selected.live} className="button button-outline"><Globe2 size={16}/> Visit the project</ExtLink>}</div></div></>}</DialogContent></Dialog>
 </div>
}
